{
 "title": "Reforger SAT",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(reforger_sat_exporter_uptime_seconds,server)"
    }
   }
  ]
 },
 "panels": [
  { "title": " $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(reforger_sat_exporter_uptime_seconds[30m])/(1800)",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Server FPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "reforger_sat_exporter_frames_per_second{server=~\"$server\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "rate(reforger_sat_exporter_events_total{server=~\"$server\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Players and AI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "reforger_sat_exporter_player_count{server=~\"$server\"}",
     "legendFormat": "Players"
    },
    {
     "expr": "reforger_sat_exporter_ai_characters{server=~\"$server\"}",
     "legendFormat": "AI Charcters"
    }
   ]
  },
  {
   "title": "Registered Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "reforger_sat_exporter_registered_entities{server=~\"$server\"}",
     "legendFormat": "Entities"
    },
    {
     "expr": "reforger_sat_exporter_registered_groups{server=~\"$server\"}",
     "legendFormat": "Groups"
    },
    {
     "expr": "reforger_sat_exporter_registered_systems{server=~\"$server\"}",
     "legendFormat": "System"
    },
    {
     "expr": "reforger_sat_exporter_registered_tasks{server=~\"$server\"}",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reforger_sat_exporter_uptime_seconds{server=~\"$server\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Time since last stats update",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-reforger_sat_exporter_updated{server=~\"$server\"}",
     "legendFormat": "  "
    }
   ]
  }
 ]
}